### ISSUE TITLE
🪟 Packager un `msi`

### ISSUE THREAD

**Issue by adriens** [opt-nc/mobitag-cli#41]
# ❔ Contexte

Ce ticket est dans la suite de : 

- #14 

[`goreleaser` dans sa version free ne supporte pas le build des msi](https://goreleaser.com/customization/msi/) : 

![Image](https://github.com/user-attachments/assets/2108e79c-f17b-48f9-9363-3dd6567bc8a6)

Les avantages de délivrer un msi sont : 

![Image](https://github.com/user-attachments/assets/d85f59c0-fed7-4438-94d3-d1b65f1682e4)

👇 

![Image](https://github.com/user-attachments/assets/696f5121-f613-4864-bb79-be0ed4ee8ee4)

# 🎯   Action

Dans notre contexte où l'exe contient tout le nécessaire, on devrait pouvoir utiliser la GH Action [Build Windows Installer MSI from `exe` file](https://github.com/marketplace/actions/build-windows-installer-msi-from-exe-file) : 

```yaml
      - name: Build Windows Installer MSI from exe file
        uses: AliceOh/CreateWindowsInstaller@1.0.0
        with:
          exefile: 'helloworld.exe'
```

- [ ] Utiliser l'exe généré par `goreleaser`, produire le `msi` avec, et attacher le msi comme asset de la release
